/* eslint-disable @typescript-eslint/no-floating-promises */
/* eslint-disable @typescript-eslint/no-misused-promises */
import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import { useRouter } from "next/router";
import { api } from "~/utils/api";
import { useForm } from "react-hook-form";

const ListingView = () => {
  const router = useRouter();
  const { register, handleSubmit, reset } = useForm<{ message: string }>();

  const listing = api.listings.get.useQuery(
    {
      listingId: router.query.id as string,
    },
    {
      enabled: !!router.query.id,
    }
  );

  const listingItem = listing.data;

  const user = useUser();

  const sendMessage = api.listings.sendMessage.useMutation();

  if (!listingItem) return null;

  return (
    <>
      <Head>
        <title>{listingItem.name}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col justify-start gap-12 bg-gray-800">
        <div className="container mx-auto flex max-w-screen-xl flex-col gap-12 p-4 text-white">
          <h1 className="mt-12 text-4xl font-bold">{listingItem.name}</h1>
          <p className="text-gray-400">{listingItem.description}</p>
          <p className="text-gray-400">$ {listingItem.price}</p>

          {user.isSignedIn && (
            <form
              className="flex flex-col gap-4"
              onSubmit={handleSubmit((formData) => {
                sendMessage
                  .mutateAsync({
                    //mutate doesnt retrun anything while mutateAsync returns a promise
                    message: formData.message,
                    listingId: listingItem.id,
                  })
                  .then(() => {
                    reset(); //reset the form
                  });
              })}
            >
              <div>
                <label
                  htmlFor="name"
                  className="text-md mb-2 block font-medium text-white"
                >
                  Message
                </label>
                <textarea
                  id="name"
                  className="block w-full rounded-lg bg-gray-700 p-2.5 text-sm"
                  {...register("message", { required: true })}
                />
              </div>
              <button className="inline-flex items-center justify-center rounded-lg bg-blue-700 px-3 py-2 text-center text-lg font-medium text-white hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                Send Message
              </button>
            </form>
          )}
        </div>
      </main>
    </>
  );
};

export default ListingView;
